//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredential) DeepCopyInto(out *CivoObjectStoreCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredential.
func (in *CivoObjectStoreCredential) DeepCopy() *CivoObjectStoreCredential {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CivoObjectStoreCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialConnectionDetails) DeepCopyInto(out *CivoObjectStoreCredentialConnectionDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialConnectionDetails.
func (in *CivoObjectStoreCredentialConnectionDetails) DeepCopy() *CivoObjectStoreCredentialConnectionDetails {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialConnectionDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialList) DeepCopyInto(out *CivoObjectStoreCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CivoObjectStoreCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialList.
func (in *CivoObjectStoreCredentialList) DeepCopy() *CivoObjectStoreCredentialList {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CivoObjectStoreCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialObservation) DeepCopyInto(out *CivoObjectStoreCredentialObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialObservation.
func (in *CivoObjectStoreCredentialObservation) DeepCopy() *CivoObjectStoreCredentialObservation {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialSpec) DeepCopyInto(out *CivoObjectStoreCredentialSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(string)
		**out = **in
	}
	out.ConnectionDetails = in.ConnectionDetails
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialSpec.
func (in *CivoObjectStoreCredentialSpec) DeepCopy() *CivoObjectStoreCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialStatus) DeepCopyInto(out *CivoObjectStoreCredentialStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialStatus.
func (in *CivoObjectStoreCredentialStatus) DeepCopy() *CivoObjectStoreCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialStatus)
	in.DeepCopyInto(out)
	return out
}
