apiVersion: ip.civo.crossplane.io/v1alpha1
kind: CivoIP
metadata:
  name: test-crossplane-ip
spec:
  providerConfigRef:
    name: civo-provider
---
apiVersion: instance.civo.crossplane.io/v1alpha1
kind: CivoInstance
metadata:
  name: test-crossplane-instance
spec:
  instanceConfig:
    diskImage: ubuntu-focal
    region: FRA1
    size: g3.large
    hostname: myCrossplaneInstance
    reserved_ip: test-crossplane-ip
    tags:
      - crossplane
      - civo
    sshPubKeyRef:
      namespace: default
      name: ssh-key-secret
      key: ssh-publickey
  providerConfigRef:
    name: civo-provider
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: default
data:
  ssh-publickey: <pubkey in base64>
type: Opaque