apiVersion: objectstorecredentials.civo.crossplane.io/v1alpha1
kind: CivoObjectStoreCredentials
metadata:
  name: test-crossplane-object-store-credentials
spec:
  name: test-cred
  connectionDetails:
    connectionSecretNamePrefix: "credential-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider