//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentials) DeepCopyInto(out *CivoObjectStoreCredentials) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentials.
func (in *CivoObjectStoreCredentials) DeepCopy() *CivoObjectStoreCredentials {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CivoObjectStoreCredentials) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialsList) DeepCopyInto(out *CivoObjectStoreCredentialsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CivoObjectStoreCredentials, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialsList.
func (in *CivoObjectStoreCredentialsList) DeepCopy() *CivoObjectStoreCredentialsList {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CivoObjectStoreCredentialsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialsObservation) DeepCopyInto(out *CivoObjectStoreCredentialsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialsObservation.
func (in *CivoObjectStoreCredentialsObservation) DeepCopy() *CivoObjectStoreCredentialsObservation {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialsSpec) DeepCopyInto(out *CivoObjectStoreCredentialsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.SecretAccessKeyID != nil {
		in, out := &in.SecretAccessKeyID, &out.SecretAccessKeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialsSpec.
func (in *CivoObjectStoreCredentialsSpec) DeepCopy() *CivoObjectStoreCredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CivoObjectStoreCredentialsStatus) DeepCopyInto(out *CivoObjectStoreCredentialsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CivoObjectStoreCredentialsStatus.
func (in *CivoObjectStoreCredentialsStatus) DeepCopy() *CivoObjectStoreCredentialsStatus {
	if in == nil {
		return nil
	}
	out := new(CivoObjectStoreCredentialsStatus)
	in.DeepCopyInto(out)
	return out
}
